### ISSUE TITLE
结合nuxt开发，报document is not defined

### ISSUE THREAD

**Issue by mingliao** [sunshineJi/amaze-vue#11]
## 结合nuxt开发ssr web网站，报document is not defined
您好，请问一下，我现在使用amaze-vue 结合 [nuxt](https://nuxtjs.org/)开发，将amaze-vue 作为插件引入。代码结构如下。
![](https://note.youdao.com/yws/public/resource/25a314442a4ca732e2b3d617b1c6d2ca/xmlnote/2AA932A351374C41A07DE4404A0DAF2B/25629)
*amaze-vue.js*代码如下:
```
import Vue from 'vue'
import AmazeVue from 'amaze-vue';
import 'amaze-vue/dist/amaze-vue.css';

export default () => {
  Vue.use(AmazeVue);
}

```

在nuxt.config.js中引入插件
```
  plugins: [
    '@/plugins/amaze-vue'
  ],
```
package.json已经引入最新的amaze-vue
```
  "dependencies": {
    "amaze-vue": "^1.1.12",
    "nuxt": "^1.0.0"
  },
```
然后再*page/index*启动页面做如下测试。
```
<template>
<am-button @click="notify">默认按钮</am-button>
</template>
<script>
  ...
methods:{
	notify(){
		this.$notify({
                    message: '你点击了确认'
                });
	}
...
</script>
```
项目启动的时候报错：
![](https://note.youdao.com/yws/public/resource/25a314442a4ca732e2b3d617b1c6d2ca/xmlnote/3E337F6B4365428A91DE3CBD222D6F20/25631)

如果要结合nuxt，如何使用amaze-vue，谢谢了了。^_^

**Comment by mingliao** [comment]
刚刚看了下官网的介绍[plugin_clientside](https://nuxtjs.org/guide/plugins#client-side-only)可以使用非ssr方式引入。
```
 plugins: [
    {src: '@/plugins/amaze-vue',ssr:false}
  ],
```
已经解决这个问题了。不过如果能支持ssr的方式，效果更好。希望作者早日支持。

**Comment by SmokingRabbit** [comment]
66666~  抽空我加一下

**Comment by mingliao** [comment]
@sunshineJi  谢啦。
