### ISSUE TITLE
Safari 下 DatePicker 组件的日期列表错误

### ISSUE THREAD

**Issue by pingshiguo** [sunshineJi/amaze-vue#12]
`DatePicker`组件在 Safari 中的日期排序如下图：
<img width="260" alt="2018-11-05 14 41 18" src="https://user-images.githubusercontent.com/19699114/47981975-e69f7d00-e108-11e8-885d-ff6b822959ff.png">
图中上月最后四天（28、29、30、31）并没有补齐，翻阅`DatePicker`组件源码时，在`date.vue`中发现以下逻辑：
<img width="575" alt="2018-11-05 14 34 11" src="https://user-images.githubusercontent.com/19699114/47982116-7f35fd00-e109-11e8-883e-f9698823fce3.png">
代码中生成`week`时使用的是：
```javascript
week = new Date(year + "-" + month + "-" + 1).getDay();
```
经测试发现，初始化`Date`，在 Safari 中支持`yyyy-MM-dd`格式，需要把`new Date(year + "-" + month + "-" + 1)`中的`1`前面补零，也就是`new Date(year + "-" + month + "-" + "01")`，Saifari 可以正确识别此日期格式，测试如下：
<img width="362" alt="2018-11-05 15 08 34" src="https://user-images.githubusercontent.com/19699114/47982968-b0fc9300-e10c-11e8-8ee0-129c9fe51ce3.png">
此外还有一种合适的做法可以避免此类情况：
<img width="402" alt="2018-11-05 15 11 15" src="https://user-images.githubusercontent.com/19699114/47983056-12246680-e10d-11e8-808e-4cbbe438a855.png">
本文抛砖引玉，文中如有不足之处，希望大家批评指正，希望能够尽早修复此组件BUG。

**Comment by SmokingRabbit** [comment]
非常感谢，最近正在开发新的组件库~ 是否有兴趣加入~

**Comment by pingshiguo** [comment]
感谢采纳！请问新的组件库是关于哪方面的？

**Comment by SmokingRabbit** [comment]
@pingshiguo ts + vue
