### ISSUE TITLE
Object sm,md,lg has no method 'includes'

### ISSUE THREAD

**Issue by ZengGuanBao** [sunshineJi/amaze-vue#14]
Object sm,md,lg has no method 'includes'
![image](https://user-images.githubusercontent.com/21127114/50622064-83ce3480-0f45-11e9-922e-c9b03361eacc.png)

**Comment by SmokingRabbit** [comment]
这是用哪个组件的时候报的错？

**Comment by ZengGuanBao** [comment]
已经改好了，在IE中不支持字符串的includes()方法，建议用indexOf()替换

**Comment by Lostsory** [comment]
移动端navItem点击时候，导航面板可以收回吗

**Comment by SmokingRabbit** [comment]
@ZengGuanBao polyfill

**Comment by SmokingRabbit** [comment]
@Lostsory 我记得是可以的，如果有问题QQ群里沟通吧，回复的比较及时
