### ISSUE TITLE
Select组件: 支持label->value传入

### ISSUE THREAD

**Issue by evalor** [sunshineJi/amaze-vue#7]
支持Select Option的选项label和实际的value不同

应用场景: 
{label: '中通快递', value: 'ZTO'},
{label: '申通快递', value: 'STO'},
{label: '圆通快递', value: 'YTO'},

**Comment by SmokingRabbit** [comment]
组件内是支持的，除关键字段外，用户可以随意扩展，选中后会返回整个对象
