### ISSUE TITLE
导航二级菜单

### ISSUE THREAD

**Issue by sansansine** [sunshineJi/amaze-vue#8]
貌似当前导航只有一级菜单，导航的二级菜单怎么处理呢

**Comment by SmokingRabbit** [comment]
方便加QQ群沟通帮你解决吗？

**Comment by sansansine** [comment]
1419569411,方便给个简单的二级导航例子吗？

**Comment by SmokingRabbit** [comment]
加文档里面的群 https://sunshineji.github.io/amaze-vue-docs/
